## Primary Database (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app_user
quarkus.datasource.password=app_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pathio_shortener

## Schema Generation
quarkus.hibernate-orm.database.generation=update

## Telemetry
quarkus.analytics.disabled=true

## Caffeine Cache
quarkus.cache.caffeine."urls".maximum-size=10000
quarkus.cache.caffeine."urls".expire-after-access=2H